API,ENH: rbf: FitError: change cv_kwds, fit_opt: add brute method
FitError: the cv_kwds now comply with
sklearn.model_selection.RepeatedKFold: use `n_splits` and `n_repeats`
instead of custom `ns` and `nr`. This also simplifies passing additional
kwds thru to RepeatedKFold such as `random_state`, which was not
possible before.

FitError: add __call__() method.

fit_opt: add scipy.optimize.brute(), a.k.a. "grid search" a.k.a. nested
loop.